package com.lxs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setUserAccount(java.lang.String userAccount) {
		set("user_account", userAccount);
		return (M)this;
	}
	
	public java.lang.String getUserAccount() {
		return getStr("user_account");
	}

	public M setUserPass(java.lang.String userPass) {
		set("user_pass", userPass);
		return (M)this;
	}
	
	public java.lang.String getUserPass() {
		return getStr("user_pass");
	}

	public M setUserCode(java.lang.String userCode) {
		set("user_code", userCode);
		return (M)this;
	}
	
	public java.lang.String getUserCode() {
		return getStr("user_code");
	}

	public M setUserSex(java.lang.Integer userSex) {
		set("user_sex", userSex);
		return (M)this;
	}
	
	public java.lang.Integer getUserSex() {
		return getInt("user_sex");
	}

	public M setUserImg(java.lang.String userImg) {
		set("user_img", userImg);
		return (M)this;
	}
	
	public java.lang.String getUserImg() {
		return getStr("user_img");
	}

	public M setUserNickname(java.lang.String userNickname) {
		set("user_nickname", userNickname);
		return (M)this;
	}
	
	public java.lang.String getUserNickname() {
		return getStr("user_nickname");
	}

	public M setUserAuto(java.lang.String userAuto) {
		set("user_auto", userAuto);
		return (M)this;
	}
	
	public java.lang.String getUserAuto() {
		return getStr("user_auto");
	}

	public M setUserTel(java.lang.String userTel) {
		set("user_tel", userTel);
		return (M)this;
	}
	
	public java.lang.String getUserTel() {
		return getStr("user_tel");
	}

	public M setUserAuth(java.lang.Integer userAuth) {
		set("user_auth", userAuth);
		return (M)this;
	}
	
	public java.lang.Integer getUserAuth() {
		return getInt("user_auth");
	}

	public M setUserApply(java.lang.Integer userApply) {
		set("user_apply", userApply);
		return (M)this;
	}
	
	public java.lang.Integer getUserApply() {
		return getInt("user_apply");
	}

	public M setUserHome(java.lang.String userHome) {
		set("user_home", userHome);
		return (M)this;
	}
	
	public java.lang.String getUserHome() {
		return getStr("user_home");
	}

	public M setUserDates(java.util.Date userDates) {
		set("user_dates", userDates);
		return (M)this;
	}
	
	public java.util.Date getUserDates() {
		return get("user_dates");
	}

}
