package com.lxs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseChapter<M extends BaseChapter<M>> extends Model<M> implements IBean {

	public M setChapterId(java.lang.Integer chapterId) {
		set("chapter_id", chapterId);
		return (M)this;
	}
	
	public java.lang.Integer getChapterId() {
		return getInt("chapter_id");
	}

	public M setChapterTypes(java.lang.Integer chapterTypes) {
		set("chapter_types", chapterTypes);
		return (M)this;
	}
	
	public java.lang.Integer getChapterTypes() {
		return getInt("chapter_types");
	}

	public M setChapterTypesM(java.lang.String chapterTypesM) {
		set("chapter_types_m", chapterTypesM);
		return (M)this;
	}
	
	public java.lang.String getChapterTypesM() {
		return getStr("chapter_types_m");
	}

	public M setChapterName(java.lang.String chapterName) {
		set("chapter_name", chapterName);
		return (M)this;
	}
	
	public java.lang.String getChapterName() {
		return getStr("chapter_name");
	}

	public M setChapterBook(java.lang.Integer chapterBook) {
		set("chapter_book", chapterBook);
		return (M)this;
	}
	
	public java.lang.Integer getChapterBook() {
		return getInt("chapter_book");
	}

	public M setChapterAuthor(java.lang.Integer chapterAuthor) {
		set("chapter_author", chapterAuthor);
		return (M)this;
	}
	
	public java.lang.Integer getChapterAuthor() {
		return getInt("chapter_author");
	}

	public M setChapterView(java.lang.Integer chapterView) {
		set("chapter_view", chapterView);
		return (M)this;
	}
	
	public java.lang.Integer getChapterView() {
		return getInt("chapter_view");
	}

	public M setChapterAuto(java.lang.String chapterAuto) {
		set("chapter_auto", chapterAuto);
		return (M)this;
	}
	
	public java.lang.String getChapterAuto() {
		return getStr("chapter_auto");
	}

	public M setChapterContent(java.lang.String chapterContent) {
		set("chapter_content", chapterContent);
		return (M)this;
	}
	
	public java.lang.String getChapterContent() {
		return getStr("chapter_content");
	}

	public M setChapterDates(java.util.Date chapterDates) {
		set("chapter_dates", chapterDates);
		return (M)this;
	}
	
	public java.util.Date getChapterDates() {
		return get("chapter_dates");
	}

}
