package com.lxs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTypes<M extends BaseTypes<M>> extends Model<M> implements IBean {

	public M setTypesId(java.lang.Integer typesId) {
		set("types_id", typesId);
		return (M)this;
	}
	
	public java.lang.Integer getTypesId() {
		return getInt("types_id");
	}

	public M setTypesName(java.lang.String typesName) {
		set("types_name", typesName);
		return (M)this;
	}
	
	public java.lang.String getTypesName() {
		return getStr("types_name");
	}

	public M setTypesLevel(java.lang.Integer typesLevel) {
		set("types_level", typesLevel);
		return (M)this;
	}
	
	public java.lang.Integer getTypesLevel() {
		return getInt("types_level");
	}

	public M setTypesHot(java.lang.Integer typesHot) {
		set("types_hot", typesHot);
		return (M)this;
	}
	
	public java.lang.Integer getTypesHot() {
		return getInt("types_hot");
	}

	public M setTypesDates(java.util.Date typesDates) {
		set("types_dates", typesDates);
		return (M)this;
	}
	
	public java.util.Date getTypesDates() {
		return get("types_dates");
	}

}
