package com.lxs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFocus<M extends BaseFocus<M>> extends Model<M> implements IBean {

	public M setFocusId(java.lang.Integer focusId) {
		set("focus_id", focusId);
		return (M)this;
	}
	
	public java.lang.Integer getFocusId() {
		return getInt("focus_id");
	}

	public M setFocusUser(java.lang.Integer focusUser) {
		set("focus_user", focusUser);
		return (M)this;
	}
	
	public java.lang.Integer getFocusUser() {
		return getInt("focus_user");
	}

	public M setFocusAuthor(java.lang.Integer focusAuthor) {
		set("focus_author", focusAuthor);
		return (M)this;
	}
	
	public java.lang.Integer getFocusAuthor() {
		return getInt("focus_author");
	}

	public M setFocusTypes(java.lang.Integer focusTypes) {
		set("focus_types", focusTypes);
		return (M)this;
	}
	
	public java.lang.Integer getFocusTypes() {
		return getInt("focus_types");
	}

	public M setFocusDates(java.util.Date focusDates) {
		set("focus_dates", focusDates);
		return (M)this;
	}
	
	public java.util.Date getFocusDates() {
		return get("focus_dates");
	}

}
