package com.lxs.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("book", "book_id", Book.class);
		arp.addMapping("chapter", "chapter_id", Chapter.class);
		arp.addMapping("focus", "focus_id", Focus.class);
		arp.addMapping("types", "types_id", Types.class);
		arp.addMapping("mail", "mail_id", Mail.class);
		arp.addMapping("tip", "tip_id", Tip.class);
		arp.addMapping("user", "user_id", User.class);
		arp.addMapping("comment", "comment_id", Comment.class);
	}
}

