package com.lxs.common.model;

import com.lxs.common.model.base.BaseChapter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Chapter extends BaseChapter<Chapter> {
	public static final Chapter dao = new Chapter().dao();
}
