package com.lxs.common.model;

import com.lxs.common.model.base.BaseFocus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Focus extends BaseFocus<Focus> {
	public static final Focus dao = new Focus().dao();
}
