package com.lxs.common.model;

import com.lxs.common.model.base.BaseMail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mail extends BaseMail<Mail> {
	public static final Mail dao = new Mail().dao();
}
