package com.lxs.common.model;

import com.lxs.common.model.base.BaseTypes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Types extends BaseTypes<Types> {
	public static final Types dao = new Types().dao();
}
